version: "3.9"

services:
  kong:
    image: kong:latest
    container_name: kong-gateway
    restart: always
    ports:
      - "8000:8000"   # Cổng HTTP cho API Gateway
      - "8443:8443"   # Cổng HTTPS cho API Gateway
      - "8001:8001"   # Cổng Admin API (chỉ dùng nội bộ)
      - "8444:8444"   # Cổng HTTPS Admin API
    environment:
      KONG_LOG_LEVEL: debug

      KONG_DATABASE: "off"  # Chạy ở chế độ không dùng database
      KONG_DECLARATIVE_CONFIG: "/kong/kong.yml"  # Đọc config từ file
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong.yml:/kong/kong.yml  # Mount file cấu hình Kong
    networks:
      - kong-net
  
  is_go:
    image: jinergenkai/hh-is-go
    container_name: is_go
    build: ./HH.Identity
    ports:
      - "9999:9999"
    env_file:
      - ./HH.Identity/.env
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge